### PR TITLE
Pseudo Q tables

### PR DESCRIPTION
**Pull request by aaronstockdill**
Introduce pseudo-Q tables, which are Q tables "transformed" into other representations.

### CODE REVIEW

**Comment by danielraggi** [comment]
Correspondences can have imports as target, so think about what to transfer to a pseudo Q table when one is found.

**Comment by danielraggi** [comment]
the merge of master into this branch is apparently successful.
However, the generation of pseudo-Q tables is still not working. Maybe it has to do with the new strange attributes I've added to tables, but who knows.

**Comment by danielraggi** [comment]
pseudo Q tables can now be generated. Errors are logged, but those are issues to fix in the future. For the moment it works reasonably well.

**Comment by aaronstockdill** [comment]
Because the stopping bug of not generating correct CSVs for unknown properties is handled, perhaps this can be merged with master?

**Pull request merged**
